---
# Role definition to allow listing pods but deny viewing secrets
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: sre-role
rules:
  - apiGroups: [""]               # Core API group
    resources: ["secrets"]         # Allow access to pods
    verbs: ["list","get"]             # Allow listing pods
  - apiGroups: [""]               # Core API group
    resources: ["pods"]         # Allow access to pods
    verbs: ["list"]             # Allow listing pods

---
# RoleBinding to bind the "sre" group to the "sre-role"
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: sre-rolebinding
subjects:
  - kind: Group                   # Binding applies to a group
    name: sre                    # Group name is "sre"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role                     # Refers to a Role
  name: sre-role                 # Role name is "sre-role"
  apiGroup: rbac.authorization.k8s.io

